<?php 
require_once("includes/libchart/classes/model/Point.php");
require_once("includes/libchart/classes/model/DataSet.php");
require_once("includes/libchart/classes/model/XYDataSet.php");
require_once("includes/libchart/classes/model/XYSeriesDataSet.php");
require_once("includes/libchart/classes/view/primitive/Padding.php");
require_once("includes/libchart/classes/view/primitive/Rectangle.php");
require_once("includes/libchart/classes/view/primitive/Primitive.php");
require_once("includes/libchart/classes/view/text/Text.php");
require_once("includes/libchart/classes/view/color/Color.php");
require_once("includes/libchart/classes/view/color/ColorSet.php");
require_once("includes/libchart/classes/view/color/Palette.php");
require_once("includes/libchart/classes/view/axis/Bound.php");
require_once("includes/libchart/classes/view/axis/Axis.php");
require_once("includes/libchart/classes/view/plot/Plot.php");
require_once("includes/libchart/classes/view/caption/Caption.php");
require_once("includes/libchart/classes/view/chart/Chart.php");
require_once("includes/libchart/classes/view/chart/BarChart.php");
require_once("includes/libchart/classes/view/chart/VerticalBarChart.php");
require_once("includes/libchart/classes/view/chart/HorizontalBarChart.php");
require_once("includes/libchart/classes/view/chart/LineChart.php");
require_once("includes/libchart/classes/view/chart/PieChart.php");

